### ISSUE TITLE
Zonulet NFT Marketplace

### ISSUE THREAD

**Issue by Agin-DropDisco** [filecoin-project/devgrants#1088]
# Open Grant Proposal: `Zonulet`

**Proposal Category:** `app-dev`

**Proposer:** `Agin-DropDisco`

## Proposal Overview

<p align="justify">
Zonulet is a decentralized marketplace that uses most of the IPFS/FILECOIN technology to store all nfts files from each user and using Harmony (ONE) Blockchain for every transactions. Zonulet Marketplace does not store nft file data from each user using a backend or server side like other nft marketplaces do, all nfts data from each user can be fully accessed by anyone other than the user from Zonulet by pulling it from IPFS/FILECOIN and we uses an end-to-end solution concept with DeFi and NFT elements that make it easier for every user to make transactions in just a few clicks.
</p>

### Problem and Solution
<p align="justify">
In its development, each of us has a fascination for collecting valuable, unique and different items. This can be handcrafted art, football cards with favorite athletes, or things that will benefit us in the present or the future with things we enjoy. To ensure safe storage of every artist/art collector, Zonulet will make sure to use IPFS/Filecoin technology to lock and protect every NFT on a decentralized network. Blockchain technology working with IPFS/Filecoin is the future and the way to truly own your valuables and keep them safe. Example: If you post any picture, video, or any file to Facebook, Instagram or youtube that doesn’t follow company guidelines, or is not approved by the team, they can remove it from the site without your permission. This, in a way, destroys all of your content . Private servers also hold the ability to alter the original image, or even replace it. If the hosted file for your NFT is removed off of a centralized platform, it is corrupted and impossible to reacquire the original, verified data. With the use of IPFS/Filecoin technology in Zonulet this will change 180 degrees, all content that you have uploaded will be completely yours and cannot be deleted or destroyed. Zonulet is Decentralized NFT Marketplace and did not use a private server like other nft marketplaces do because private server will keeps your NFTs centralized. This means that the specific server the user has stored their item on has all the power over that said item. Essentially, the user gives up their right to “own” the NFT’s image and data, if the server decided to shut down, or did not approve of certain content, they could remove it or destroy it. On the other hand, as value continues to increase on certain collectibles, if a centralized server has control over the item, you risk losing it. Consider the financial investment of your collection and think about how your NFTs might be recovered if the private servers they reside on went offline.
</p>

### Flow
<img src="https://raw.githubusercontent.com/zonulet-io/Zonulet-Assets/main/social-icons/diagram_fixed2.png" />

## Mission
- [x] **Improves the functionality of NFTs by giving thema real use case within Filecoin & Zonulet Platform.**
- [x] **Bring the new experience of Minting NFT and Staking in the same place.**
- [x] **Building a Unique NFT Marketplace with profit potential.**
- [x] **Be the main part in the Filecoin ecosystem.**
- [x] **Create an end-to-end solution that attracts more users & Developer.**

### **Milestone 1  | Time 1 month**

- [x] **Development/Updates and add more features to the zonulet marketplace**
- [x] **Build our own RPC Node that can request more than 10K/block for each transaction**
- [x] **Roadmap Detailed & Idea for building ZonuletNFT Gamify**
- [x] **Create Unit Tests alongside Development**
- [x] **Venue + Event Management**
- [x] **Marketing**

###  **Milestone 2  | Time 2 month**
- [x] **Developing the alpha version of the Zonulet NFT Gamify**
- [x] **Build and test NFT Gamify**
- [x] **Start Workshop and Mentoring**
- [x] **Launched NFT Gamify to Polygon/Harmony testnet and can be tested at least to 200 people**
- [x] **Legal, Compliance & Audit**
- [x] **Tutorial series post on youtube [ How we build Zonulet with IPFS/FIlecoin ]** 

## **How funds will be utilized:**
<img src="https://raw.githubusercontent.com/zonulet-io/Zonulet-Assets/main/bdgt.png" />

## Our public Roadmap

- [x] **Documentation and Forum Launch** ✅ [Completed](https://docs.zonulet.io) 
- [x] **NFT Minting Website Launch**           ✅ [Completed](https://zonulet.io) 
- [x] **AMM Dex Launch**                             ✅ [Completed](https://dex.zonulet.io) 
- [x] **Contract Audited v1**                         ✅ [Completed](https://github.com/zonulet-io/Audit-Contracts)

### **Metrics for success**

**We believe that the biggest value of Zonulet is the community, who are at the same time users, investors, designer and developers. We have two growth plans for both cases: if the Launch event is Successful or Unsuccessful. Growth strategy and efforts will be different for both options, but both targets are more than achievable.**

- [x] **1K ~ 20K user in the last three month**
- [x] **2K ~ 500k transaction in the quartal one & two (Q1~Q2)**

*Noted: Zonulet will fully use IPFS/FIlECOIN to store/retrieve assets such as videos, images, 3D models combined with serverside, all Projects are expected to be completed over the next 3 ~ 14 months for all Zonulet Product*

## **Zonulet Team**

**As a Zonulet Teams we have secured multiple rewards from public blockchain/hackathon & hack event, including**
- Gitcoin Hackathon: Harmony: Bridging TradFi to DeFi
- Gitcoin Hackathon: Polygon, Badger DAO, Skynet, Graph, Grant 9, 10, 11 Hackathon
- Gitcoin Hackathon: Hello World Polkadot (Moonbeam, Polkadot, Kusama, Phala Network )
- Encode Hack Club, DevPost and more.

**1.Adinda Ratnawati Ridwan**

- [x] RPA Production Support at  PT. AXA Services Indonesia
- [x] Programer and Security audited at PT.Primalogic Global Technology
- [Linkedin](https://www.linkedin.com/in/adinda-ratnawati-ridwan-20a980170/)
- [Github](https://github.com/adinda-ratna)

**2.Agin DropDisco** 
- [x] Fullstack Developer
- [Linkedin](https://www.linkedin.com/in/agin-dropdisco-5555b7171/)
- [Github](https://github.com/Agin-DropDisco)

**3.Fahreza Rahman**
- [x] Frontend & .NET Developer at PT. Aksata Global Solution
- [Linkedin](https://www.linkedin.com/in/fahreza-rahman-b8220a186/)
- [Github](https://github.com/ximore-code)

**4.Agus Wildhan**
- [x] Senior Solidity Contracts Developer
- [x] IT Production Support and Analyst
- [Linkedin](https://www.linkedin.com/in/chikall/)
- [Github](https://github.com/daffacode)

## External Links

**Website** https://zonulet.io
**Github**  https://github.com/zonulet-io
**Discord** https://discord.gg/4aNj64n7bf
**Email** gin.dropdisco@gmail.com 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  yes

**In July 2022 we received a $5K grant at Nextstep Microgrant for the first phase development process of ZooHarmony NFT which was migrated  into Zonulet Marketplace** *see: https://github.com/filecoin-project/devgrants/issues/644*

**Comment by Agin-DropDisco** [comment]
Hello @realChainLife after zonulet was totally  integrated into Filecoin we have more than 500 unique users who have used zonulet in the last seven days
<p align="center">
<img src="https://raw.githubusercontent.com/zonulet-io/Zonulet-Assets/main/dappradar-stats.png" />
</p>

And now we are waiting for your feedback to continue and develop this project. Thank you!
> Dappradar Sources: https://dappradar.com/harmony/marketplaces/zonulet

**Comment by realChainLife** [comment]
Hi @Agin-DropDisco thanks for your patience with our feedback here and for that update. I'd appreciate your thoughts on some open questions from the initial review: 
- 500 unique users is great. What's the user onboarding plan that will get you up to 20k active users in 3 months? 
- What's the traction on the other Zonulet products like the DexSwap? 
- Marketplace https://zonulet.io/explore/exploreall is not retrieving data fast enough, is this a standard retrieval issue, where is the data currently stored?

**Comment by Agin-DropDisco** [comment]
Thanks for the question @realChainLife 

heres the answer:

1. We got more than 500 users with zero marketing and promotion, so with the funds we get from this grants, we will use 30% of it for promotions, incentives and  create various events such as airdrop and nft competition to attracts more users to zonulet. We will make sure to get 20K+ daily users in the next 3 months

2. DexSwap itself was build in August 2021 for Harmony Bridging TradFi to DeFi hackathon and now is used for staking facility on the zonulet marketplace and validates price comparisons such as NFT prices and swaps through pairs that we created and integrated with the chainlink price feed

     - [x] How we use the DexSwap onto zonulet marketplace contracts: 
            https://github.com/zonulet-io/Utility/blob/882cce9ad952726141c8179b51aeadb31f8884e2/Zonulet.sol#L1330

     - [x] How we use Chainlink price feed/oracle : 
            https://github.com/zonulet-io/Utility/blob/882cce9ad952726141c8179b51aeadb31f8884e2/ZonuletOracle.sol#L207

     - [x]  Winner ann from harmony hackathon: 
           https://twitter.com/harmonyprotocol/status/1447654724061122560
           https://twitter.com/harmonyprotocol/status/1447654702204678146?s=20


3. And yes it takes 20~30 seconds to fetch the latest minted nft, random nft, newly purchased nft and etc. because we are using public harmony rpc, therefore, in milestone one, we wrote that we will build our own rpc to make it faster to fetch all nft data,we have also built an api  indexer using nginx as an alternative to store metadata and retrieve it quickly to the  zonulet marketplace
     - [x] Sources
          https://github.com/zonulet-io/api-indexer
         https://rpc.zonulet.io/harmony.json

**Comment by Agin-DropDisco** [comment]
hello @ErinOCon @realChainLife Is there any update about this grant pls ? 😞

**Comment by ErinOCon** [comment]
HI @Agin-DropDisco, thank you for checking in! This grant is still under review, but we expect an update will be available soon.

**Comment by ErinOCon** [comment]
HI @Agin-DropDisco, thank you again for your proposal and for your time with the additional information. We will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
